(()=>{
const E=window.WineBlindEngine,C=E.candidate,profiles=E.profiles,byGrape=E.byGrape;
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const sat=[['F',1],['M−',2],['M',3],['M+',4],['E',5]]; const state={structure:{},families:new Set(),signatures:new Set(),exacts:new Set(),training:null,last:null};
const fmt=x=>Number(x).toFixed(1).replace('.',',');
const satWord=x=>{if(x<=.4)return 'Non détecté';if(x<1.5)return 'Faible';if(x<2.5)return 'Moyen−';if(x<3.5)return 'Moyen';if(x<4.5)return 'Moyen+';return 'Élevé';};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
function tabs(){ $$('.tabs button').forEach(b=>b.onclick=()=>{$$('.tabs button').forEach(x=>x.classList.remove('active'));$$('.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');$('#'+b.dataset.tab).classList.add('active');if(b.dataset.tab==='grapes')renderGrapes();if(b.dataset.tab==='history')renderHistory();}); }
function structureUI(){const el=$('#structureFields');el.innerHTML='';E.axes.forEach(a=>{const d=document.createElement('div');d.className='structure-input';d.innerHTML=`<div class="label">${a}</div><div class="sat-options">${sat.map(([lab,v])=>`<button class="sat-option" data-axis="${a}" data-v="${v}">${lab}</button>`).join('')}</div>`;el.appendChild(d)});$$('.sat-option').forEach(b=>b.onclick=()=>{const a=b.dataset.axis,v=+b.dataset.v;state.structure[a]=state.structure[a]===v?null:v;$$(`.sat-option[data-axis="${a}"]`).forEach(x=>x.classList.toggle('active',state.structure[a]===+x.dataset.v));});}
function markerCatalog(){const out={family:new Set(),signature:new Set(),exact:new Set()};C.marker_dictionary.forEach(m=>out[m.kind]?.add(m.item));return Object.fromEntries(Object.entries(out).map(([k,v])=>[k,[...v].sort((a,b)=>a.localeCompare(b,'fr'))]));}
const catalog=markerCatalog();
function renderAromas(filter=''){const root=$('#aromaPicker'),q=filter.trim().toLowerCase();root.innerHTML='';[['family','Familles'],['signature','Signatures'],['exact','Descripteurs précis']].forEach(([kind,title])=>{const items=catalog[kind].filter(x=>x.toLowerCase().includes(q));if(!items.length)return;const sec=document.createElement('div');sec.className='aroma-group';sec.innerHTML=`<div class="aroma-group-title">${title}</div><div class="chips">${items.map(x=>`<button class="chip ${state[kind+'s']?.has(x)?'selected':''}" data-kind="${kind}" data-item="${esc(x)}">${esc(x)}</button>`).join('')}</div>`;root.appendChild(sec)});$$('#aromaPicker .chip').forEach(b=>b.onclick=()=>{const set=state[b.dataset.kind+'s'];set.has(b.dataset.item)?set.delete(b.dataset.item):set.add(b.dataset.item);renderAromas($('#aromaSearch').value);renderSelected();});}
function renderSelected(){const el=$('#aromaSelected');const vals=[];for(const k of ['families','signatures','exacts'])state[k].forEach(x=>vals.push([k,x]));el.innerHTML=vals.length?vals.map(([k,x])=>`<span class="chip selected">${esc(x)}</span>`).join(''):'';}
function observation(){return {structure:Object.fromEntries(E.axes.map(a=>[a,state.structure[a]??null])),families:[...state.families],signatures:[...state.signatures],exacts:[...state.exacts],coherenceTokens:[...state.exacts]};}
function relative(v,max){return max>0?Math.max(0,Math.min(100,100*v/max)):0;}
function why(r){const goodS=r.st.detail.filter(x=>x.inRange).sort((a,b)=>b.sim-a.sim).slice(0,3).map(x=>`${x.axis.toLowerCase()} cohérente`);const ex=r.ar.matchedExacts.slice(0,3);const gen=r.ar.matchedGeneric.slice(0,2);const warn=r.st.detail.filter(x=>!x.inRange).sort((a,b)=>a.sim-b.sim).slice(0,2).map(x=>`${x.axis.toLowerCase()} atypique`);return {good:[...ex,...gen,...goodS].slice(0,6),warn};}
function doScore(){const obs=observation();if(!Object.values(obs.structure).some(x=>x!=null)&&!obs.families.length&&!obs.signatures.length&&!obs.exacts.length){alert('Renseigne au moins un élément de structure ou un arôme.');return;}const res=E.score(obs);state.last={obs,res,at:new Date().toISOString()};renderResults(res);saveHistory();}
function renderResults(res){const root=$('#diagnosticResults');root.classList.remove('hidden');const top=res.grapes[0],max=top?.I||1,w=why(top);root.innerHTML=`<div class="result-hero"><div class="rank">DIAGNOSTIC PRINCIPAL</div><div class="grape">${esc(top.profile.grape)}</div><div class="origin">${esc(top.profile.style)} · ${esc(top.profile.geography||'')}</div><div class="scoreline"><div class="scorebar"><i style="width:${relative(top.I,max)}%"></i></div><strong>${relative(top.I,max).toFixed(0)}</strong></div><div class="score-note">Indice relatif de compatibilité — ce n’est pas une probabilité.</div><div class="why-box"><strong>Pourquoi ce résultat ?</strong><div class="why-list">${w.good.map(x=>`<span class="why-tag">✓ ${esc(x)}</span>`).join('')}${w.warn.map(x=>`<span class="why-tag">△ ${esc(x)}</span>`).join('')}</div></div></div>`;
root.innerHTML+=rankSection('Top 10 cépages',res.grapes.slice(0,10),'grape',max);root.innerHTML+=rankSection('Top 10 origines',res.profiles.slice(0,10),'origin',res.profiles[0]?.I||1);bindResults();root.scrollIntoView({behavior:'smooth',block:'start'});}
function rankSection(title,arr,type,max){return `<div class="results-section"><div class="results-title"><h2>${title}</h2><span>${type==='origin'?'Profil régional / style':'Cépage'}</span></div><div class="rank-list">${arr.map((r,i)=>`<button class="${type==='origin'?'origin-card':'result-card'} ${i<3?'top3':''}" data-type="${type}" data-id="${type==='origin'?r.profile.profile_id:esc(r.profile.grape)}"><span class="rank-pill">${i+1}</span><span class="result-main"><strong>${esc(type==='origin'?r.profile.style:r.profile.grape)}</strong><small>${esc(type==='origin'?(r.profile.grape+' · '+(r.profile.geography||'')):r.profile.style)}</small></span><span class="result-score">${relative(r.I,max).toFixed(0)}<small>indice</small></span></button>`).join('')}</div></div>`;}
function bindResults(){$$('.result-card[data-type="grape"]').forEach(b=>b.onclick=()=>openGrape(b.dataset.id));$$('.origin-card[data-type="origin"]').forEach(b=>b.onclick=()=>openOrigin(+b.dataset.id));}
function axisCards(struct){return `<div class="identity-structure">${E.axes.map(a=>{const x=struct[a];return `<div class="identity-axis"><div class="axis-name">${a}</div><div class="sat-word">${satWord(x.center)}</div><div class="precise">${fmt(x.center)}</div><div class="range">Plage typique [${fmt(x.L)}–${fmt(x.U)}]</div></div>`}).join('')}</div>`;}
function markerHTML(markers){const core=markers.filter(m=>m.context!=='TERTIARY_OPTIONAL').sort((a,b)=>b.typicality-a.typicality);const ex=core.filter(m=>m.kind==='exact').slice(0,12),gen=core.filter(m=>m.kind!=='exact').slice(0,12),ter=markers.filter(m=>m.context==='TERTIARY_OPTIONAL').slice(0,10);return `<div class="marker-section"><h3>Descripteurs précis</h3><div class="marker-line">${ex.length?ex.map(m=>`<span class="marker exact">${esc(m.item)} · ${fmt(m.typicality)}</span>`).join(''):'<span class="muted">Aucun exact spécifique matérialisé pour ce profil.</span>'}</div></div><div class="marker-section"><h3>Familles & signatures</h3><div class="marker-line">${gen.map(m=>`<span class="marker">${esc(m.item)} · ${fmt(m.typicality)}</span>`).join('')}</div></div>${ter.length?`<div class="marker-section"><h3>Évolution / tertiaire</h3><div class="marker-line">${ter.map(m=>`<span class="marker">${esc(m.item)}</span>`).join('')}</div></div>`:''}`;}
function openOrigin(id){const p=profiles.find(x=>x.profile_id===id);if(!p)return;showModal(`${p.style}`,`<div class="modal-subtitle">${esc(p.grape)} · ${esc(p.geography||'Origine non précisée')}</div><div class="origin-meta"><div class="meta-box"><small>Cépage</small><strong>${esc(p.grape)}</strong></div><div class="meta-box"><small>Style / origine</small><strong>${esc(p.style)}</strong></div></div><h3>Structure interne C2-C2</h3>${axisCards(p.structure)}${markerHTML(p.markers)}<div class="warning" style="margin-top:15px">Les valeurs à 0,1 décrivent le profil interne du moteur. La saisie de dégustation reste volontairement au format SAT.</div>`);}
function grapeAggregate(g){const ps=byGrape[g];const s={};E.axes.forEach(a=>{const cs=ps.map(p=>p.structure[a].center).sort((x,y)=>x-y),med=cs[Math.floor(cs.length/2)];s[a]={center:med,L:Math.min(...ps.map(p=>p.structure[a].L)),U:Math.max(...ps.map(p=>p.structure[a].U))};});const marker=new Map();ps.forEach(p=>p.markers.forEach(m=>{const k=m.kind+':'+m.item;if(!marker.has(k)||marker.get(k).typicality<m.typicality)marker.set(k,m)}));return {ps,structure:s,markers:[...marker.values()]};}
function openGrape(g){const a=grapeAggregate(g);showModal(g,`<div class="modal-subtitle">Fiche cépage · ${a.ps.length} profil${a.ps.length>1?'s':''} régional/style</div><h3>Structure représentative</h3>${axisCards(a.structure)}<p class="muted" style="margin-top:8px">Centre = médiane des profils ; plage = enveloppe des profils C2-C2.</p>${markerHTML(a.markers)}<div class="marker-section"><h3>Origines & styles</h3><div class="profile-list">${a.ps.map(p=>`<button class="profile-link" data-profile="${p.profile_id}"><strong>${esc(p.style)}</strong><small>${esc(p.geography||'')}</small></button>`).join('')}</div></div>`);$$('.profile-link').forEach(b=>b.onclick=()=>openOrigin(+b.dataset.profile));}
function showModal(title,body){$('#modalTitle').textContent=title;$('#modalBody').innerHTML=body;$('#modal').classList.remove('hidden');document.body.style.overflow='hidden';}
function closeModal(){$('#modal').classList.add('hidden');document.body.style.overflow='';}
function renderGrapes(){const q=$('#grapeSearch').value.toLowerCase().trim();const gs=Object.keys(byGrape).filter(g=>{if(g.toLowerCase().includes(q))return true;return byGrape[g].some(p=>(p.style+' '+(p.geography||'')).toLowerCase().includes(q));}).sort((a,b)=>a.localeCompare(b,'fr'));$('#grapeList').innerHTML=gs.map(g=>`<button class="grape-row" data-grape="${esc(g)}"><span><strong>${esc(g)}</strong><small>${byGrape[g].length} profil${byGrape[g].length>1?'s':''}</small></span><span>›</span></button>`).join('');$$('.grape-row').forEach(b=>b.onclick=()=>openGrape(b.dataset.grape));}
function saveHistory(){let h=JSON.parse(localStorage.getItem('wb-history')||'[]');const top=state.last.res.grapes[0];h.unshift({at:state.last.at,grape:top.profile.grape,style:top.profile.style});localStorage.setItem('wb-history',JSON.stringify(h.slice(0,50)));}
function renderHistory(){const h=JSON.parse(localStorage.getItem('wb-history')||'[]');$('#historyList').innerHTML=h.length?h.map(x=>`<div class="history-item"><strong>${esc(x.grape)}</strong> · ${esc(x.style)}<div class="muted">${new Date(x.at).toLocaleString('fr-FR')}</div></div>`).join(''):'<div class="empty">Aucun diagnostic enregistré.</div>';}
function reset(){state.structure={};state.families.clear();state.signatures.clear();state.exacts.clear();$$('.sat-option').forEach(x=>x.classList.remove('active'));$('#aromaSearch').value='';renderAromas();renderSelected();$('#diagnosticResults').classList.add('hidden');}
function training(){const p=profiles[Math.floor(Math.random()*profiles.length)];state.training=p;$('#trainingPrompt').innerHTML='<strong>Profil tiré.</strong><br><span class="muted">Déguste, renseigne ton diagnostic dans l’onglet Diagnostic, puis reviens révéler le vin.</span>';$('#revealTraining').disabled=false;$('#trainingReveal').classList.add('hidden');}
function reveal(){const p=state.training;if(!p)return;$('#trainingReveal').classList.remove('hidden');$('#trainingReveal').innerHTML=`<div class="card" style="margin-top:12px"><strong>${esc(p.grape)}</strong><div>${esc(p.style)} · ${esc(p.geography||'')}</div><button class="secondary" style="margin-top:10px;width:100%" id="openTrainProfile">Voir la fiche</button></div>`;$('#openTrainProfile').onclick=()=>openOrigin(p.profile_id);}
function install(){let deferred;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferred=e;$('#installBtn').classList.remove('hidden');});$('#installBtn').onclick=async()=>{if(deferred){deferred.prompt();await deferred.userChoice;deferred=null;$('#installBtn').classList.add('hidden');}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('./sw.js'));}
// init
tabs();structureUI();renderAromas();renderSelected();renderGrapes();renderHistory();$('#aromaSearch').oninput=e=>renderAromas(e.target.value);$('#clearAromas').onclick=()=>{state.families.clear();state.signatures.clear();state.exacts.clear();renderAromas($('#aromaSearch').value);renderSelected();};$('#scoreBtn').onclick=doScore;$('#resetBtn').onclick=reset;$('#grapeSearch').oninput=renderGrapes;$('#clearHistory').onclick=()=>{localStorage.removeItem('wb-history');renderHistory();};$('#newTraining').onclick=training;$('#revealTraining').onclick=reveal;$('#modalClose').onclick=closeModal;$('#modal').onclick=e=>{if(e.target.id==='modal')closeModal();};document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal();});install();
})();