
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let MODEL=null, RELEASE=null, selected={families:new Set(),signatures:new Set(),exacts:new Set(),coherence:new Set()}, structure={};let deferredPrompt=null,trainingProfile=null;
const SAT=[['ND',null],['F',1],['M-',2],['M',3],['M+',4],['E',5]];
const AXES=[['acidite','Acidité'],['tanins','Tanins'],['alcool','Alcool'],['corps','Corps'],['couleur','Couleur / intensité visuelle'],['intensite','Intensité aromatique*']];
const esc=s=>(s??'').toString().replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[m]));
async function init(){[MODEL,RELEASE]=await Promise.all([fetch('data/model.json').then(r=>r.json()),fetch('data/release.json').then(r=>r.json())]);renderStructure();renderAromas();renderGrapes();renderHistory();bind();if('serviceWorker'in navigator)navigator.serviceWorker.register('sw.js');}
function bind(){ $$('.tabs button').forEach(b=>b.onclick=()=>{ $$('.tabs button').forEach(x=>x.classList.toggle('active',x===b));$$('.tab').forEach(x=>x.classList.toggle('active',x.id===b.dataset.tab));});$('#scoreBtn').onclick=score;$('#resetBtn').onclick=reset;$('#clearAromas').onclick=()=>{selected={families:new Set(),signatures:new Set(),exacts:new Set(),coherence:new Set()};renderAromas()};$('#aromaSearch').oninput=renderAromas;$('#grapeSearch').oninput=renderGrapes;$('#clearHistory').onclick=()=>{localStorage.removeItem('wineBlindHistory');renderHistory()};$('#newTraining').onclick=newTraining;$('#revealTraining').onclick=revealTraining;window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').classList.remove('hidden')});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').classList.add('hidden')}}}
function renderStructure(){const box=$('#structureFields');box.innerHTML='';AXES.forEach(([key,label])=>{const d=document.createElement('div');d.innerHTML=`<div class="field-title">${label}${key==='intensite'?' <span class="muted">(mémorisée, neutre dans C2-C2)</span>':''}</div><div class="sat-options">${SAT.map(([l,v])=>`<button class="${v==null?'na':''}" data-axis="${key}" data-v="${v??''}">${l}</button>`).join('')}</div>`;box.appendChild(d)});$$('.sat-options button').forEach(b=>b.onclick=()=>{const k=b.dataset.axis,v=b.dataset.v===''?null:+b.dataset.v;structure[k]=v;$$(`[data-axis="${k}"]`).forEach(x=>x.classList.toggle('active',x===b))})}
function markerGroups(){const d=MODEL.marker_dictionary;return {Familles:d.filter(x=>x.kind==='family').map(x=>x.item),Signatures:d.filter(x=>x.kind==='signature').map(x=>x.item),Exacts:d.filter(x=>x.kind==='exact').map(x=>x.item),'Cohérence':MODEL.coherence_observation_vocabulary.filter(x=>!x.profile_marker).map(x=>x.token)}}
function renderAromas(){const q=($('#aromaSearch')?.value||'').toLowerCase();const groups=markerGroups();const picker=$('#aromaPicker');picker.innerHTML='';for(const [title,items] of Object.entries(groups)){const key=title==='Familles'?'families':title==='Signatures'?'signatures':title==='Exacts'?'exacts':'coherence';const shown=[...new Set(items)].filter(x=>x.toLowerCase().includes(q)).slice(0,q?100:35);if(!shown.length)continue;const div=document.createElement('div');div.className='aroma-group';div.innerHTML=`<h3>${title}</h3><div class="chips">${shown.map(x=>`<button class="chip ${selected[key].has(x)?'on':''}" data-kind="${key}" data-item="${esc(x)}">${esc(x)}</button>`).join('')}</div>`;picker.appendChild(div)}$$('#aromaPicker .chip').forEach(b=>b.onclick=()=>{const s=selected[b.dataset.kind];s.has(b.dataset.item)?s.delete(b.dataset.item):s.add(b.dataset.item);renderAromas()});$('#aromaSelected').innerHTML=[...Object.entries(selected)].flatMap(([k,s])=>[...s].map(x=>`<button class="chip" data-kind="${k}" data-item="${esc(x)}">${esc(x)} ×</button>`)).join('');$$('#aromaSelected .chip').forEach(b=>b.onclick=()=>{selected[b.dataset.kind].delete(b.dataset.item);renderAromas()})}
function inputObject(){return {structure:{acidite:structure.acidite??null,tanins:structure.tanins??null,alcool:structure.alcool??null,corps:structure.corps??null,couleur:structure.couleur??null,intensite:structure.intensite??null},families:[...selected.families],signatures:[...selected.signatures],exacts:[...selected.exacts],coherence:[...selected.coherence]}}
function score(){const inp=inputObject();if(!Object.values(inp.structure).some(v=>v!=null)&&![...selected.families,...selected.signatures,...selected.exacts,...selected.coherence].length){alert('Renseigne au moins un élément de structure ou un arôme.');return}const ranked=WineBlindEngine.rank(MODEL,inp).slice(0,10);renderResults(ranked,inp);saveHistory(ranked,inp)}
function renderResults(ranked,inp){const box=$('#diagnosticResults');box.classList.remove('hidden');const top=ranked[0];const max=Math.max(...ranked.map(x=>x.score.I),.001);box.innerHTML=`<div class="result-head"><div class="muted">Diagnostic principal</div><div class="winner">${esc(top.grape)}</div><div>${esc(top.profile.geography||top.profile.style||'')}</div><div class="style">${esc(top.profile.style||'')} · A ${top.score.A.toFixed(3)} · S ${top.score.S_eff.toFixed(3)}${top.score.C?` · C ${top.score.C>=0?'+':''}${top.score.C.toFixed(3)}`:''}</div></div><h2>Top 10</h2>`+ranked.map((x,i)=>`<div class="result-row"><div class="rank">${i+1}</div><div><strong>${esc(x.grape)}</strong><div class="style">${esc(x.profile.geography||'')} · ${esc(x.profile.style||'')}</div><div class="bar"><i style="width:${Math.max(4,100*x.score.I/max)}%"></i></div></div><div class="score">${x.score.I.toFixed(3)}</div></div>`).join('');box.scrollIntoView({behavior:'smooth',block:'start'})}
function reset(){structure={};selected={families:new Set(),signatures:new Set(),exacts:new Set(),coherence:new Set()};renderStructure();renderAromas();$('#diagnosticResults').classList.add('hidden')}
function saveHistory(ranked,inp){const h=JSON.parse(localStorage.getItem('wineBlindHistory')||'[]');h.unshift({date:new Date().toISOString(),top:ranked.slice(0,10).map(x=>({grape:x.grape,score:x.score.I,style:x.profile.style,geo:x.profile.geography})),input:inp});localStorage.setItem('wineBlindHistory',JSON.stringify(h.slice(0,100)));renderHistory()}
function renderHistory(){const h=JSON.parse(localStorage.getItem('wineBlindHistory')||'[]');$('#historyList').innerHTML=h.length?h.map(x=>`<div class="history-item"><div class="history-date">${new Date(x.date).toLocaleString('fr-FR')}</div><strong>${esc(x.top[0]?.grape||'—')}</strong><div class="style">${x.top.slice(0,5).map((y,i)=>`${i+1}. ${esc(y.grape)}`).join(' · ')}</div></div>`).join(''):'<p class="muted">Aucun diagnostic enregistré.</p>'}
function renderGrapes(){if(!MODEL)return;const q=($('#grapeSearch')?.value||'').toLowerCase();const by=new Map();MODEL.profiles.forEach(p=>{const hay=(p.grape+' '+(p.style||'')+' '+(p.geography||'')).toLowerCase();if(q&&!hay.includes(q)&&!p.markers.some(m=>m.item.toLowerCase().includes(q)))return;if(!by.has(p.grape))by.set(p.grape,[]);by.get(p.grape).push(p)});$('#grapeList').innerHTML=[...by.entries()].sort().map(([g,ps])=>`<details class="grape-card"><summary>${esc(g)} <span class="muted">(${ps.length} profil${ps.length>1?'s':''})</span></summary>${ps.map(p=>`<div class="profile"><div class="profile-title">${esc(p.geography||p.style||'Profil')}</div><div class="style">${esc(p.style||'')}</div><div class="marker-line"><b>Structure :</b> ${Object.entries(p.structure).map(([k,v])=>`${k} ${v.center.toFixed(1)} [${v.L.toFixed(1)}–${v.U.toFixed(1)}]`).join(' · ')}</div><div class="marker-line"><b>Marqueurs :</b> ${p.markers.slice().sort((a,b)=>b.capacity-a.capacity).slice(0,10).map(m=>esc(m.item)).join(', ')}</div></div>`).join('')}</details>`).join('')||'<p class="muted">Aucun résultat.</p>'}
function newTraining(){trainingProfile=MODEL.profiles[Math.floor(Math.random()*MODEL.profiles.length)];$('#trainingPrompt').innerHTML='Profil tiré. Fais ton diagnostic dans l’onglet <b>Diagnostic</b>, puis reviens révéler la réponse.';$('#revealTraining').disabled=false;$('#trainingReveal').classList.add('hidden');$$('.tabs button').find(b=>b.dataset.tab==='diagnostic').click();reset()}
function revealTraining(){if(!trainingProfile)return;const ranked=WineBlindEngine.rank(MODEL,inputObject());const rank=ranked.findIndex(x=>x.grape===trainingProfile.grape)+1;const d=$('#trainingReveal');d.classList.remove('hidden');d.innerHTML=`<div class="result-head"><div class="muted">Réponse</div><div class="winner">${esc(trainingProfile.grape)}</div><div>${esc(trainingProfile.geography||trainingProfile.style||'')}</div><div class="style">Ton diagnostic place ce cépage au rang ${rank||'—'}.</div></div>`}
init().catch(e=>{console.error(e);document.body.innerHTML='<main><div class="card"><h2>Erreur de chargement</h2><p>'+esc(e.message)+'</p></div></main>'});
