(()=>{const D=WSET_DATA,T=WSET_TREE,$=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const S={type:"Rouge",g:{acid:"",tannin:"",alcohol:"",body:"",color:"",intensity:"",fruit:"",signature:"",texture:""},o:{climate:"",maturity:"",oak:"",marker:""},gr:[],or:[],tree:{cur:"1",stack:[]}};
const L={acid:"Acidité",tannin:"Tanins",alcohol:"Alcool",body:"Corps",color:"Couleur",intensity:"Intensité",fruit:"Fruit",signature:"Signature",texture:"Texture"},sat=["","F","M-","M","M+","E"],lev=v=>({"F":1,"M-":2,"M":3,"M+":4,"E":5}[v]||0),cmp=d=>d<=.01?1:d<=.5?.92:d<=1?.82:d<=1.5?.65:d<=2?.42:d<=2.5?.2:.05,has=(a,b)=>(a||"").toLowerCase().includes((b||"").toLowerCase());
function satField(k,l){let w=document.createElement("div");w.className="sat-field";w.innerHTML=`<div class="sat-label">${l}</div>`;let b=document.createElement("div");b.className="sat-buttons";sat.forEach(v=>{let x=document.createElement("button");x.type="button";x.className="sat-btn"+(S.g[k]===v?" active":"");x.textContent=v||"?";x.onclick=()=>{S.g[k]=v;forms();calc()};b.append(x)});w.append(b);return w}
function sel(k,l,opts,target){let w=document.createElement("div");w.className="field",a=document.createElement("label"),s=document.createElement("select");a.textContent=l;opts.forEach(v=>{let o=document.createElement("option");o.value=v;o.textContent=v||"Non renseigné";s.append(o)});s.value=S[target][k];s.onchange=()=>{S[target][k]=s.value;calc()};w.append(a,s);return w}
function forms(){let a=$("#structureFields");a.innerHTML="";[["acid","Acidité"],["tannin","Tanins"],["alcohol","Alcool"],["body","Corps"],["color","Couleur / intensité"],["intensity","Intensité aromatique"]].forEach(x=>{if(x[0]==="tannin"&&S.type==="Blanc")return;a.append(satField(...x))});let m=$("#markerFields");m.innerHTML="";[["fruit","Famille de fruit",D.options.fruit],["signature","Marqueur signature",D.options.signature],["texture","Texture / élevage",D.options.texture]].forEach(x=>m.append(sel(...x,"g")));let f=$("#originFields");f.innerHTML="";[["climate","Climat perçu",D.options.climate],["maturity","Maturité du fruit",D.options.maturity],["oak","Bois",D.options.oak],["marker","Marqueur dominant",D.options.originMarker]].forEach(x=>f.append(sel(...x,"o")))}
function geval(g){if(g.type!==S.type)return{score:0,reasons:[]};let w=D.weights.grape,n=0,d=0,c=0,r=[];[["acid","acid",w.acid],["tannin","tannin",w.tannin],["alcohol","alcohol",w.alcohol],["body","body",w.body],["color","color",w.color],["intensity","intensity",w.intensity]].forEach(([sk,gk,wt])=>{if(sk==="tannin"&&S.type==="Blanc")return;let o=lev(S.g[sk]);if(!o)return;let q=Number(g[gk]);if(!Number.isFinite(q))return;let z=Math.abs(q-o);n+=wt*5*cmp(z);d+=wt*5;if(z<=.5)r.push({t:L[sk]+" très cohérent",w:0});else if(z>=2){r.push({t:L[sk]+" en tension",w:1});if(["acid","tannin","alcohol","body"].includes(sk))c++}});[["fruit","fruitCompatible",w.fruit,.3],["signature","signaturesCompatible",w.signature,.1],["texture","textureCompatible",w.texture,.3]].forEach(([sk,gk,wt,res])=>{let o=S.g[sk];if(!o)return;let hit=has(g[gk],o);n+=wt*5*(hit?1:res);d+=wt*5;if(hit)r.push({t:L[sk]+" compatible",w:0});else if(sk==="signature")r.push({t:"Signature non typique",w:1})});if(!d)return{score:0,reasons:[]};let s=n/d*100;if(c>=4)s*=.65;else if(c===3)s*=.8;return{score:s,reasons:r}}
function ofit(o){let w=D.weights.origin,n=0,d=0,c=0;[["acid","acid",w.acid],["tannin","tannin",w.tannin],["alcohol","alcohol",w.alcohol],["body","body",w.body],["color","color",w.color]].forEach(([sk,ok,wt])=>{if(sk==="tannin"&&S.type==="Blanc")return;let a=lev(S.g[sk]);if(!a)return;let q=Number(o[ok]);if(!Number.isFinite(q))return;let z=Math.abs(q-a);n+=wt*5*cmp(z);d+=wt*5;if(["acid","tannin","alcohol","body"].includes(sk)&&z>=2)c++});[["climate","climate",w.climate,{"Frais":1,"Tempéré":2,"Chaud":3}],["maturity","maturity",w.maturity,{"Frais":1,"Mûr":2,"Très mûr / séché":3}],["oak","oak",w.oak,{"Faible":1,"Modéré":2,"Marqué":3}]].forEach(([sk,ok,wt,map])=>{let v=S.o[sk];if(!v)return;let a=map[v],q=Number(o[ok]);if(!a||!Number.isFinite(q))return;let z=Math.abs(q-a);n+=wt*5*(z===0?1:z===1?.82:.5);d+=wt*5});if(S.o.marker){n+=w.marker*5*(o.marker===S.o.marker?1:.35);d+=w.marker*5}if(!d)return 0;let s=n/d*100;if(c>=4)s*=.65;else if(c===3)s*=.8;return s}
function calc(){S.gr=D.grapes.map(g=>({...g,...geval(g)})).filter(g=>g.type===S.type&&g.score>0).sort((a,b)=>b.score-a.score).slice(0,10);let map=new Map(S.gr.map((g,i)=>[g.name,{score:g.score,rank:i+1}])),w=D.weights.origin;S.or=D.origins.filter(o=>map.has(o.grape)).map(o=>{let p=map.get(o.grape),fit=ofit(o);return{...o,grapeScore:p.score,fit,score:w.grapePrior*p.score+w.styleFit*fit}}).sort((a,b)=>b.score-a.score).slice(0,10);results();inherited()}
function reasons(r){r=(r||[]).slice(0,4);return r.length?`<div class="reason-box"><div class="reason-title">Pourquoi ce candidat ?</div><div class="reason-chips">${r.map(x=>`<span class="reason-chip ${x.w?"warn":""}">${x.t}</span>`).join("")}</div></div>`:""}
function card(x,i,orig){let e=document.createElement("div");e.className="result-card";e.innerHTML=`<div class="result-top"><span class="rank">${i+1}</span><div><div class="result-name">${orig?x.style:x.name}</div>${orig?`<div class="result-origin">${x.grape} · ${x.region}</div>`:""}</div><span class="score">${Math.round(x.score)}</span></div><div class="bar"><span style="width:${Math.max(2,Math.min(100,x.score))}%"></span></div><div class="result-meta">${orig?(x.diagnostic||""):(x.keyMarker||"")}</div>${orig?`<div class="reason-box"><div class="reason-chips"><span class="reason-chip">Cépage ${Math.round(x.grapeScore)}</span><span class="reason-chip neutral">Style ${Math.round(x.fit)}</span></div></div>`:reasons(x.reasons)}`;e.onclick=()=>orig?showO(x):showG(x);return e}
function results(){let a=$("#grapeResults");a.innerHTML=S.gr.length?"":'<div class="empty">Renseigne au moins un critère.</div>';S.gr.forEach((x,i)=>a.append(card(x,i,0)));$("#grapeCount").textContent=S.gr.length?S.gr.length+" candidats":"";let b=$("#originResults");b.innerHTML=S.or.length?"":'<div class="empty">Le Top 10 apparaît après le diagnostic cépage.</div>';S.or.forEach((x,i)=>b.append(card(x,i,1)))}
function inherited(){let e=$("#inheritedSummary");e.innerHTML="";[["Acidité","acid"],["Tanins","tannin"],["Alcool","alcohol"],["Corps","body"],["Couleur","color"]].forEach(([l,k])=>{if(k==="tannin"&&S.type==="Blanc"||!S.g[k])return;let p=document.createElement("span");p.className="pill";p.textContent=l+" · "+S.g[k];e.append(p)});if(S.gr[0]){let p=document.createElement("span");p.className="pill";p.textContent="Top 1 · "+S.gr[0].name;e.append(p)}}
const met=(l,v)=>`<div class="metric"><b>${v??"—"}</b><span>${l}</span></div>`,blk=(l,v)=>v?`<div class="detail-block"><b>${l}</b><p>${v}</p></div>`:"";
function showG(g){$("#detailType").textContent=g.type+" · Cépage";$("#detailTitle").textContent=g.name;$("#detailBody").innerHTML=`<div class="detail-grid">${met("Acidité",g.acid)}${g.type==="Rouge"?met("Tanins",g.tannin):""}${met("Alcool",g.alcohol)}${met("Corps",g.body)}${met("Couleur",g.color)}${met("Intensité",g.intensity)}</div>${reasons(g.reasons)}${blk("Marqueur clé",g.keyMarker)}${blk("Différenciation",g.differentiation)}${blk("Contre-indices",g.redFlags)}${blk("Arômes",g.primaryAromas)}${blk("Régions",g.regions)}${blk("Confusions",g.confusions)}`;$("#detailDialog").showModal()}
function showO(o){$("#detailType").textContent=o.grape+" · Origine";$("#detailTitle").textContent=o.style;$("#detailBody").innerHTML=`<div class="detail-grid">${met("Score",Math.round(o.score))}${met("Cépage",Math.round(o.grapeScore))}${met("Style",Math.round(o.fit))}</div>${blk("Région",o.region)}${blk("Pourquoi ça colle",o.diagnostic)}${blk("À vérifier",o.differentiation)}${blk("Confusions",o.confusions)}`;$("#detailDialog").showModal()}
function tab(n){$$(".tab").forEach(x=>x.classList.toggle("active",x.dataset.tab===n));$$(".screen").forEach(x=>x.classList.toggle("active",x.id==="tab-"+n));if(n==="history")histRender();scrollTo({top:0,behavior:"smooth"})}
function ref(q=""){let l=$("#referenceList");l.innerHTML="";q=q.toLowerCase();D.grapes.filter(g=>!q||g.name.toLowerCase().includes(q)||(g.synonyms||"").toLowerCase().includes(q)).slice(0,100).forEach(g=>{let r=document.createElement("div");r.className="ref-row";r.innerHTML=`<div><strong>${g.name}</strong><br><small>${g.type}</small></div><span>›</span>`;r.onclick=()=>showG(g);l.append(r)})}
function treeRender(){let n=T[S.tree.cur];$("#treeStep").textContent="Étape "+n.id;$("#treeQuestion").textContent=n.q;$("#treeTip").textContent=n.tip;$("#treeOrientation").classList.add("hidden");$("#treeBack").style.visibility=S.tree.stack.length?"visible":"hidden"}
function treeAns(y){let n=T[S.tree.cur],txt=y?n.yesText:n.noText,nx=y?n.yesNext:n.noNext;S.tree.stack.push({id:n.id,a:y?"Oui":"Non",text:txt});$("#treeOrientation").textContent=txt;$("#treeOrientation").classList.remove("hidden");trail();setTimeout(()=>{if(nx==="BACK")back();else if(nx==="ORIGIN")tab("origin");else if(nx==="GRAPE")tab("grape");else if(T[nx]){S.tree.cur=nx;treeRender();trail()}},650)}
function back(){let x=S.tree.stack.pop();if(x)S.tree.cur=x.id;treeRender();trail()}function trail(){let e=$("#treeTrail");e.innerHTML="";S.tree.stack.slice(-6).forEach(x=>{let d=document.createElement("div");d.className="trail-item";d.innerHTML=`<b>${x.id} · ${x.a}</b> — ${x.text}`;e.append(d)})}
const HK="wineBlindHistoryV2",hist=()=>{try{return JSON.parse(localStorage.getItem(HK)||"[]")}catch{return[]}};
function openSave(){let d=new Date();$("#wineDate").value=d.toISOString().slice(0,10);$("#saveDialog").showModal()}
function save(ev){ev.preventDefault();let g=S.gr[0],o=S.or[0],r={id:Date.now(),date:$("#wineDate").value,name:$("#wineName").value.trim(),vintage:$("#wineVintage").value.trim(),actualGrape:$("#actualGrape").value.trim(),actualOrigin:$("#actualOrigin").value.trim(),notes:$("#wineNotes").value.trim(),type:S.type,topGrape:g?g.name:"",topGrapeScore:g?Math.round(g.score):null,top3:S.gr.slice(0,3).map(x=>x.name),topOrigin:o?o.style:""};let h=hist();h.unshift(r);localStorage.setItem(HK,JSON.stringify(h));$("#saveDialog").close();$("#saveForm").reset();tab("history")}
function histRender(){let h=hist(),k=h.filter(x=>x.actualGrape),a=k.filter(x=>x.actualGrape.toLowerCase()===x.topGrape.toLowerCase()).length,b=k.filter(x=>x.top3.some(g=>g.toLowerCase()===x.actualGrape.toLowerCase())).length;$("#historyStats").innerHTML=`<div class="stat-card"><b>${h.length}</b><span>Dégustations</span></div><div class="stat-card"><b>${k.length?Math.round(a/k.length*100)+"%":"—"}</b><span>Top 1</span></div><div class="stat-card"><b>${k.length?Math.round(b/k.length*100)+"%":"—"}</b><span>Top 3</span></div>`;let l=$("#historyList");l.innerHTML=h.length?"":'<div class="empty">Aucune dégustation enregistrée.</div>';h.forEach(r=>{let d=document.createElement("div");d.className="history-card";d.innerHTML=`<div class="history-head"><div><h3>${r.name||"Dégustation sans nom"}${r.vintage?" · "+r.vintage:""}</h3><div class="history-meta">${r.date||""} · ${r.type}</div></div><button class="delete-btn" data-id="${r.id}">Supprimer</button></div><div class="history-result"><b>Diagnostic :</b> ${r.topGrape||"—"}${r.topGrapeScore?` (${r.topGrapeScore})`:""}${r.topOrigin?" · "+r.topOrigin:""}<br><b>Révélation :</b> ${r.actualGrape||"non renseignée"}${r.actualOrigin?" · "+r.actualOrigin:""}${r.notes?`<br><span class="muted">${r.notes}</span>`:""}</div>`;l.append(d)});$$(".delete-btn").forEach(b=>b.onclick=()=>{localStorage.setItem(HK,JSON.stringify(hist().filter(x=>String(x.id)!==b.dataset.id)));histRender()})}
$("#typeRed").onclick=()=>{S.type="Rouge";$("#typeRed").classList.add("active");$("#typeWhite").classList.remove("active");forms();calc()};$("#typeWhite").onclick=()=>{S.type="Blanc";S.g.tannin="";$("#typeWhite").classList.add("active");$("#typeRed").classList.remove("active");forms();calc()};$$(".tab").forEach(b=>b.onclick=()=>tab(b.dataset.tab));$("#goOrigin").onclick=()=>tab("origin");$("#closeDialog").onclick=()=>$("#detailDialog").close();$("#searchGrape").oninput=e=>ref(e.target.value);$("#treeYes").onclick=()=>treeAns(1);$("#treeNo").onclick=()=>treeAns(0);$("#treeBack").onclick=back;$("#treeRestart").onclick=()=>{S.tree={cur:"1",stack:[]};treeRender();trail()};$("#saveTasting").onclick=openSave;$("#saveTastingOrigin").onclick=openSave;$("#closeSave").onclick=()=>$("#saveDialog").close();$("#saveForm").onsubmit=save;$("#resetAll").onclick=()=>{Object.keys(S.g).forEach(k=>S.g[k]="");Object.keys(S.o).forEach(k=>S.o[k]="");S.type="Rouge";forms();calc();tab("grape")};D.grapes.forEach(g=>{let o=document.createElement("option");o.value=g.name;$("#grapeNames").append(o)});forms();ref();treeRender();histRender();calc();if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js").catch(()=>{})})();