const fs=require('fs'),vm=require('vm');global.window=global;vm.runInThisContext(fs.readFileSync(__dirname+'/engine.js','utf8'));const model=JSON.parse(fs.readFileSync(__dirname+'/data/model.json','utf8'));
function assert(x,msg){if(!x)throw new Error(msg)}
assert(model.profiles.length===203,'203 profiles');assert(new Set(model.profiles.map(p=>p.grape)).size===85,'85 grapes');assert(model.marker_dictionary.length===77,'77 markers');assert(model.marker_dictionary.filter(x=>x.kind==='exact').length===63,'63 exacts');
const empty={structure:{},families:[],signatures:[],exacts:[],coherence:[]};let r=WineBlindEngine.rank(model,empty);assert(r.length===85,'rank has 85 grapes');assert(r.every(x=>Number.isFinite(x.score.I)),'finite empty scores');
const p=model.profiles[0];const inp={structure:{acidite:p.structure['Acidité'].center,tanins:p.structure['Tanins'].center,alcool:p.structure['Alcool'].center,corps:p.structure['Corps'].center,couleur:p.structure['Couleur'].center},families:p.markers.filter(m=>m.kind==='family').slice(0,2).map(m=>m.item),signatures:p.markers.filter(m=>m.kind==='signature').slice(0,2).map(m=>m.item),exacts:p.markers.filter(m=>m.kind==='exact').slice(0,2).map(m=>m.item),coherence:[]};r=WineBlindEngine.rank(model,inp);assert(r.length===85,'rank 85 with data');assert(r.every(x=>x.score.A>=0&&x.score.A<=1),'A bounded');assert(r.every(x=>x.score.C>=-.08&&x.score.C<=.04),'C bounded');
// Direct structure center should produce perfect structure similarity on the source profile.
const sp=WineBlindEngine.structScore(p,inp);assert(Math.abs(sp.S-1)<1e-12,'center in range => S=1');assert(Math.abs(sp.kappa-1)<1e-12,'all 5 axes => kappa=1');
// Exact base hierarchy is materialized in runtime.
assert(model.engine.aroma.type_weights.exact===1.5,'exact 1.5');assert(model.engine.aroma.type_weights.signature===1.25,'signature 1.25');assert(model.engine.aroma.type_weights.family===1,'family 1');
// 203-profile deterministic execution scan using profile centers + up to 5 strongest markers.
let top10=0,top5=0,top1=0;for(const prof of model.profiles){const ms=[...prof.markers].filter(m=>m.context!=='TERTIARY_OPTIONAL').sort((a,b)=>b.capacity-a.capacity).slice(0,5);const x={structure:{acidite:prof.structure['Acidité'].center,tanins:prof.structure['Tanins'].center,alcool:prof.structure['Alcool'].center,corps:prof.structure['Corps'].center,couleur:prof.structure['Couleur'].center},families:ms.filter(m=>m.kind==='family').map(m=>m.item),signatures:ms.filter(m=>m.kind==='signature').map(m=>m.item),exacts:ms.filter(m=>m.kind==='exact').map(m=>m.item),coherence:[]};const rr=WineBlindEngine.rank(model,x);const k=rr.findIndex(y=>y.grape===prof.grape)+1;if(k===1)top1++;if(k<=5)top5++;if(k<=10)top10++;assert(rr.every(y=>Number.isFinite(y.score.I)),'all profile scan finite')}
console.log(JSON.stringify({status:'PASS',profiles:203,grapes:85,markers:77,exacts:63,synthetic_self_recognition:{top1,top5,top10}},null,2));
