import fs from 'node:fs';
import vm from 'node:vm';
import assert from 'node:assert/strict';

const read=p=>fs.readFileSync(p,'utf8');
const index=read('index.html');
const app=read('app.js');
const css=read('styles.css');
const overlay=read('v11-reset.css');
const patch=read('v11-reset-patch.js');
const sw=read('sw.js');

for(const asset of ['styles.css','v11-reset.css','data.js','v106.js','v107.js','v108.js','tree.js','app.js','c2c2-data.js','c2c2-engine.js','v11-reset-patch.js']) assert.ok(index.includes(asset),`index missing ${asset}`);
for(const feature of ['data-tab="grape"','data-tab="origin"','data-tab="tree"','data-tab="quiz"','data-tab="reference"','id="historyList"']) assert.ok(index.includes(feature),`historical UI missing ${feature}`);
assert.ok(app.length>500000,'historical app.js unexpectedly small');
for(const feature of ['WINE_LEXICON','trainingHubStats','refOrigins','wineBlindHistoryV2']) assert.ok(app.includes(feature),`historical app feature missing ${feature}`);
for(const feature of ['.sat-continuum','.training-grid','.alpha-index','.aroma-group']) assert.ok(css.includes(feature),`historical CSS feature missing ${feature}`);
for(const feature of ['openProfile','saveC2','Top 10 origines','C2-C2','rankVisual','scoreBreakdown']) assert.ok(patch.includes(feature),`V11.1.0 patch feature missing ${feature}`);
assert.ok(sw.includes('wine-blind-v11-1-0-mobile-1'),'wrong service-worker cache namespace');
assert.ok(app.includes('window.WineBlindReference=Object.freeze'),'historical grape reference is not exposed as the single identity source');
assert.ok(patch.includes('window.WineBlindReference?.openGrape(r.profile.grape)'),'Top 10 cards do not use the historical reference identity source');
assert.ok(!patch.includes('openGrapeAggregate'),'competing C2-C2 aggregate identity source still exists');
assert.ok(patch.includes('fingerprint-evidence'),'identity fingerprints omit exact descriptors');
assert.ok(patch.includes('fp-w${x.weight}'),'identity fingerprints omit prevalence 1/2/3');
assert.ok(patch.includes("const arr=fp[type]||[]"),'complete fingerprints are not installed');
assert.ok(!patch.includes('wireReference'),'reference clicks are still intercepted by a competing identity renderer');

// Mobile navigation / interaction regression guards.
assert.ok(overlay.includes('repeat(var(--sat-count),minmax(0,1fr))'),'SAT continuum does not use its real point count');
assert.ok(overlay.includes('left:calc(50% / var(--sat-count))'),'SAT left edge is not aligned to first point');
assert.ok(overlay.includes('right:calc(50% / var(--sat-count))'),'SAT right edge is not aligned to last point');
assert.ok(overlay.includes('touch-action:manipulation'),'touch targets are not hardened for iOS Safari');
assert.ok(!patch.includes("document.addEventListener('click',e=>{const ref="),'legacy global capture click listener still present');
assert.ok(!patch.includes("document.addEventListener('pointerup',schedule,true)"),'legacy global capture pointer listener still present');
assert.ok(app.includes('new CustomEvent("wineblind:diagnostic-input")'),'historical inputs do not emit the single diagnostic event');
assert.ok(patch.includes("document.addEventListener('wineblind:diagnostic-input',schedule)"),'C2-C2 does not use the single diagnostic event');
assert.ok(!patch.includes("document.addEventListener('pointerup'"),'duplicate pointer recompute listener is still active');
assert.ok(!patch.includes("document.addEventListener('change'"),'duplicate change recompute listener is still active');
assert.ok(patch.includes("Aucun repère saisi"),'misleading confidence badge was not replaced');
assert.ok(patch.includes('visibleInputCount'),'input indicator is not based on visible retained inputs');
assert.ok(!patch.includes('Pourquoi ?'),'legacy Why block is still rendered under grape candidates');
for(const tone of ['match','near','mismatch']) assert.ok(overlay.includes(`.c2-fit-chip.${tone}`),`missing ${tone} structural match colour`);
assert.ok(patch.includes('blindSignature(p.grape)'),'profile identity still replaces the blind signature with an origin/style');
assert.ok(!app.includes('x.classList.toggle("active",i<0);forms()'),'aroma descriptor tap still rebuilds the complete form');
assert.ok(!app.includes('obj[k]=chosen;forms();calc()'),'structure rail still rebuilds the complete form on pointerup');
assert.ok(app.includes('function deferCalc(){document.dispatchEvent'),'historical ranking still runs alongside C2-C2');
assert.ok(app.includes('forms();deferCalc()};$("#typeWhite")'),'red/white toggle still blocks on synchronous ranking');
assert.ok(app.includes('x.classList.toggle("active",i<0);deferCalc()'),'descriptor selection still blocks on synchronous ranking');
assert.ok(patch.includes('timer=setTimeout(render,180)'),'C2-C2 burst interactions are not coalesced');
assert.ok(patch.includes('updateInputIndicator({});clearTimeout(timer)'),'input counter is not updated before deferred ranking');
assert.ok(patch.includes('rank podium podium-${i+1}'),'C2-C2 cards do not own stable podium icons');
const exactFr=vm.runInNewContext('('+patch.match(/const EXACT_FR=(\{.*?\});/s)[1]+')');
const uiExact=vm.runInNewContext('('+patch.match(/const UI_EXACT=(\{.*?\});/s)[1]+')');
assert.ok(patch.includes('metric-level-${level(r.center)}'),'C2-C2 reference metrics are not using legacy progressive color classes');
assert.ok(patch.includes('window.__C2_LAST=null'),'reset/no-signal state does not clear cached C2 result');
assert.ok(!patch.includes('refine.remove()'),'C2-C2 bridge removes historical origin fields required by forms()');
assert.ok(patch.includes('\nwire();\n})()'),'C2-C2 bridge initialization is not immediate and deterministic');
assert.ok(app.includes('Convergence · Arbre autonome'),'tree is not presented as standalone');
assert.ok(app.includes('window.WineBlindTree={restart:treeRestart}'),'tree lifecycle bridge is missing');
assert.ok(app.includes('function tab(n){$$(\".tab\").forEach'),'main navigation does not iterate over all tabs');
assert.ok(patch.includes('wireTreeLifecycle'),'red/white/reset actions do not rebuild the tree lifecycle');
assert.ok(!app.includes('syncTreeToDiagnostic'),'legacy Tree → Diagnostic coupling is still active');
assert.ok(!app.includes('treeDiagnosticCandidates'),'tree still depends on the legacy Diagnostic ranking');

const sandbox={window:{},console};
vm.createContext(sandbox);
vm.runInContext(read('c2c2-data.js'),sandbox,{filename:'c2c2-data.js'});
const C=sandbox.window.WINE_BLIND_CANDIDATE;
assert.equal(C.candidate_id,'Wine-Blind-vNext-C2-C2');
assert.equal(C.profiles.length,203);
assert.equal(new Set(C.profiles.map(p=>p.grape)).size,85);
assert.equal(C.marker_dictionary.length,77);
assert.equal(C.marker_dictionary.filter(m=>m.kind==='exact').length,63);
const canonicalExacts=new Set(C.marker_dictionary.filter(m=>m.kind==='exact').map(m=>m.item));
assert.deepEqual([...canonicalExacts].filter(x=>!exactFr[x]),[],'a canonical exact marker has no French display label');
assert.deepEqual(Object.values(uiExact).filter(x=>!canonicalExacts.has(x)),[],'a French UI mapping targets an unknown canonical exact');
for(const [label,canonical] of Object.entries({banane:'banana',chevrefeuille:'honeysuckle',mangue:'mango','poivre noir':'pepper',raisin:'raisin frais','fruits a coque':'nutty'})) assert.equal(uiExact[label],canonical,`missing French exact mapping for ${label}`);
vm.runInContext(read('c2c2-engine.js'),sandbox,{filename:'c2c2-engine.js'});
const E=sandbox.window.WineBlindEngine;
assert.ok(E&&typeof E.score==='function','engine did not initialize');
for(const canonical of new Set(Object.values(uiExact))){
  const probe=E.score({structure:{},families:[],signatures:[],exacts:[canonical],coherenceTokens:[]});
  assert.ok(probe.profiles.some(x=>x.ar.matchedExacts.includes(canonical)&&x.A>0),`French mapping ${canonical} has no scoring effect`);
}
const obs={structure:{'Acidité':4,'Tanins':4,'Alcool':4,'Corps':4,'Couleur':4},families:['Fruits noirs'],signatures:['Épicé / poivré'],exacts:['cassis','graphite'],coherenceTokens:[]};
const scored=E.score(obs);
assert.equal(scored.grapes.length,85);
assert.equal(scored.profiles.length,203);
assert.ok(scored.grapes.every(x=>Number.isFinite(x.I)&&Number.isFinite(x.A)&&Number.isFinite(x.S_eff)&&Number.isFinite(x.C)),'non-finite score');
assert.ok(scored.grapes[0].I>=scored.grapes.at(-1).I,'ranking not sorted');
const pinot=E.profiles.find(p=>p.grape==='Pinot Noir');
const pinotObs={structure:Object.fromEntries(Object.entries(pinot.structure).map(([axis,r])=>[axis,Math.round(r.center)])),families:[],signatures:[],exacts:[],coherenceTokens:[]};
const pinotResult=E.score(pinotObs).grapes.find(r=>r.profile.grape==='Pinot Noir');
assert.equal(E.score(pinotObs).grapes[0].profile.grape,'Pinot Noir','Pinot structure regression');
assert.equal(Math.round(pinotResult.st.S*100),100,'Pinot structure should be a perfect observed fit');
assert.ok(patch.includes('(3.2*r.A+r.S_eff+r.C)/available'),'displayed adequacy is not normalized to observed evidence');
console.log('Wine Blind V11.1.0 adequacy and complete fingerprint smoke test: PASS');
